--- # Master RDS instance
- name: Creating a Master  RDS instance
  local_action:
    module: rds
    command: create
    instance_name: "{{ instance_name }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    db_name: "{{ db_name }}"
    db_engine: "{{ db_engine }}"
    engine_version: 5.5.46
    vpc_security_groups: "{{ vpc_security_groups }}"
    port: 3306
    size: "{{ size }}"
    multi_zone: no
    maint_window: "Fri:01:00-Fri:01:30"
    backup_window: "02:00-02:30"
    backup_retention: 14
    upgrade: yes
    wait: yes
    wait_timeout: 3600
    username: "{{ username }}"
    password: "{{ password }}"
